### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by nguyenthienhoan** [Skittyblock/SkittyPrefs#1]
error: userInterfaceStyle is unvailable: not available on iOS 
[https://i.imgur.com/BpU44wU.png](url)

**Comment by Skittyblock** [comment]
You need to either use an iOS 13 sdk or unprohibit it in your sdk.

**Comment by nguyenthienhoan** [comment]
> Bạn cần sử dụng sdk iOS 13 hoặc không cấm nó trong sdk của bạn.

ok i was use sdk ios 13, but how about this ?
[https://i.imgur.com/XHGlGaN.png](url)
